relationships:
  - name: apmConsumesAwsMskTopic2
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "MessageBroker/Kafka/Deserialization/*"
        caseSensitive: true
    relationship:
      expires: P75M
      relationshipType: CONSUMES
      source:
        extractGuid:
        attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSMSKTOPIC2
          fields:
            - field: clusterName
              attribute: aws.clusterName
            - field: region
              attribute: aws.region
            - field: topic
              attribute: aws.topic